import type { BrandTokens, DesignBrief } from "@/lib/schema";
import { tokensToCssVars, tokensToTailwindTheme, tokensToW3C } from "@/lib/generate/tokens";

type ScaffoldOpts = {
  businessName: string;
  library: string;
  tokens: BrandTokens;
  brief: DesignBrief;
};

const LIBRARY_DEPS: Record<string, Record<string, string>> = {
  shadcn: {
    "class-variance-authority": "0.7.0",
    clsx: "2.1.1",
    "tailwind-merge": "2.4.0",
    "lucide-react": "0.424.0",
  },
  aceternity: {
    "framer-motion": "11.3.8",
  },
  mantine: {
    "@mantine/core": "7.12.0",
    "@mantine/hooks": "7.12.0",
  },
  heroui: {
    "@heroui/react": "2.4.6",
  },
  daisyui: {
    daisyui: "4.12.10",
  },
};

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 40);
}

function googleFontHref(tokens: BrandTokens): string | null {
  const families = Array.from(
    new Set(tokens.fonts.map((font) => font.family)),
  ).filter(
    (family) => !/courier|georgia|times|system-ui/i.test(family),
  );
  if (families.length === 0) return null;

  const params = families
    .map((family) => {
      const font = tokens.fonts.find((entry) => entry.family === family);
      const weights = font?.weights.join(";") ?? "400;700";
      return `family=${encodeURIComponent(family)}:wght@${weights}`;
    })
    .join("&");

  return `https://fonts.googleapis.com/css2?${params}&display=swap`;
}

function buildPackageJson(opts: ScaffoldOpts): string {
  const libraryDeps = LIBRARY_DEPS[opts.library] ?? LIBRARY_DEPS.shadcn;
  return JSON.stringify(
    {
      name: slugify(opts.businessName) || "stylus-variant",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
        lint: "next lint",
      },
      dependencies: {
        next: "14.2.5",
        react: "18.3.1",
        "react-dom": "18.3.1",
        ...libraryDeps,
      },
      devDependencies: {
        typescript: "5.5.3",
        "@types/node": "20.14.10",
        "@types/react": "18.3.3",
        "@types/react-dom": "18.3.0",
        tailwindcss: "3.4.6",
        postcss: "8.4.39",
        autoprefixer: "10.4.19",
      },
    },
    null,
    2,
  );
}

function buildLayout(opts: ScaffoldOpts): string {
  const fontLink = googleFontHref(opts.tokens);
  const linkTag = fontLink
    ? `\n        <link rel="preconnect" href="https://fonts.googleapis.com" />\n        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />\n        <link href="${fontLink}" rel="stylesheet" />`
    : "";

  return `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: ${JSON.stringify(opts.businessName)},
  description: ${JSON.stringify(`${opts.businessName} — ${opts.brief.primaryAction}`)},
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>${linkTag}
      </head>
      <body className="min-h-screen bg-[var(--color-background)] text-[var(--color-text)] font-[family-name:var(--font-body)] antialiased">
        {children}
      </body>
    </html>
  );
}
`;
}

function buildAgentsMd(opts: ScaffoldOpts): string {
  return `# AGENTS.md

## Stack
- Next.js 14 App Router
- React 18
- Tailwind CSS 3
- UI library: ${opts.library}

## Design tokens
Always read \`tokens.json\` before changing colors, typography, spacing, or radii.
Use CSS variables from \`app/globals.css\` (\`--color-*\`, \`--font-*\`, \`--spacing-*\`, \`--radius-*\`).
Do not hardcode hex values when a token exists.

## Archetype
${opts.brief.archetype} — ${opts.brief.voice}

## Motion
motionLevel: ${opts.brief.motionLevel}
`;
}

function buildReadme(opts: ScaffoldOpts): string {
  const slug = slugify(opts.businessName);
  return `# ${opts.businessName}

Generated by Stylus. Archetype: **${opts.brief.archetype}** · Library: **${opts.library}**

## Develop

\`\`\`bash
npm install
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000).

## Deploy

[![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new/clone?repository-url=https://github.com/vercel/next.js&project-name=${slug})

## Credits
- UI: ${opts.library}
- Tokens: W3C DTCG format in \`tokens.json\`
`;
}

export function buildBaseScaffold(opts: ScaffoldOpts): Record<string, string> {
  return {
    "package.json": buildPackageJson(opts),
    "tsconfig.json": JSON.stringify(
      {
        compilerOptions: {
          target: "ES2017",
          lib: ["dom", "dom.iterable", "esnext"],
          allowJs: false,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          esModuleInterop: true,
          module: "esnext",
          moduleResolution: "bundler",
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: "preserve",
          incremental: true,
          paths: { "@/*": ["./*"] },
        },
        include: ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
        exclude: ["node_modules"],
      },
      null,
      2,
    ),
    "tailwind.config.ts": tokensToTailwindTheme(opts.tokens, opts.library),
    "postcss.config.mjs": `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
`,
    "app/globals.css": `@tailwind base;
@tailwind components;
@tailwind utilities;

${tokensToCssVars(opts.tokens)}`,
    "app/layout.tsx": buildLayout(opts),
    "tokens.json": tokensToW3C(opts.tokens),
    "AGENTS.md": buildAgentsMd(opts),
    "README.md": buildReadme(opts),
  };
}
